# project/backend/api/categories/core/constants/icons.py
CATEGORY_ICONS = [
    ('food', 'Еда'),
    ('transport', 'Транспорт'),
    ('shopping', 'Шоппинг'),
    ('entertainment', 'Развлечения'),
    ('health', 'Здоровье'),
    ('education', 'Образование'),
    ('gifts', 'Подарки'),
    ('travel', 'Путешествия'),
    ('utilities', 'Коммунальные услуги'),
    ('salary', 'Зарплата'),
    ('freelance', 'Фриланс'),
    ('investment', 'Инвестиции'),
    ('business', 'Бизнес'),
    ('rent', 'Аренда'),
    ('other', 'Другое'),
    ('groceries', 'Продукты'),
    ('restaurant', 'Рестораны'),
    ('coffee', 'Кофе'),
    ('alcohol', 'Алкоголь'),
    ('fuel', 'Топливо'),
    ('taxi', 'Такси'),
    ('public_transport', 'Общественный транспорт'),
    ('clothing', 'Одежда'),
    ('electronics', 'Электроника'),
    ('books', 'Книги'),
    ('sports', 'Спорт'),
    ('beauty', 'Красота'),
    ('pharmacy', 'Аптека'),
    ('insurance', 'Страхование'),
    ('taxes', 'Налоги'),
    ('charity', 'Благотворительность'),
]
