# evercoin/backend/api/core/constants/icons.py
WALLET_ICONS = [
    ('wallet', 'Кошелек'),
    ('credit-card', 'Кредитная карта'),
    ('bank', 'Банк'),
    ('cash', 'Наличные'),
    ('piggy-bank', 'Копилка'),
    ('card', 'Карта'),
    ('money-bill', 'Деньги'),
    ('coins', 'Монеты'),
    ('savings', 'Сбережения'),
    ('investment', 'Инвестиции'),
    ('digital-wallet', 'Цифровой кошелек'),
    ('mobile-wallet', 'Мобильный кошелек'),
    ('crypto-wallet', 'Крипто-кошелек'),
    ('debit-card', 'Дебетовая карта'),
    ('prepaid-card', 'Предоплаченная карта'),
]

CATEGORY_ICONS = [
    ('shopping', 'Покупки'),
    ('food', 'Еда'),
    ('transport', 'Транспорт'),
    ('home', 'Дом'),
    ('health', 'Здоровье'),
    ('entertainment', 'Развлечения'),
    ('education', 'Образование'),
    ('salary', 'Зарплата'),
    ('gift', 'Подарок'),
    ('investment', 'Инвестиции'),
    ('travel', 'Путешествия'),
    ('utilities', 'Коммунальные услуги'),
    ('subscription', 'Подписка'),
    ('clothing', 'Одежда'),
    ('electronics', 'Электроника'),
]
