# Generated by Django 4.2.16 on 2025-08-31 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operations", "0001_initial"),
        ("categories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations",
                to="wallets.wallet",
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["user", "date"], name="operations__user_id_15b920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["user", "operation_type"], name="operations__user_id_91c19d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["user", "category"], name="operations__user_id_e719d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["user", "wallet"], name="operations__user_id_2d1e88_idx"
            ),
        ),
    ]
