# Generated by Django 4.2.16 on 2025-08-31 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Доход"), ("expense", "Расход")],
                        max_length=10,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("shopping", "Покупки"),
                            ("food", "Еда"),
                            ("transport", "Транспорт"),
                            ("home", "Дом"),
                            ("health", "Здоровье"),
                            ("entertainment", "Развлечения"),
                            ("education", "Образование"),
                            ("salary", "Зарплата"),
                            ("gift", "Подарок"),
                            ("investment", "Инвестиции"),
                            ("travel", "Путешествия"),
                            ("utilities", "Коммунальные услуги"),
                            ("subscription", "Подписка"),
                            ("clothing", "Одежда"),
                            ("electronics", "Электроника"),
                        ],
                        default="shopping",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF6B6B", "Красный"),
                            ("#4ECDC4", "Бирюзовый"),
                            ("#45B7D1", "Голубой"),
                            ("#F9A826", "Оранжевый"),
                            ("#6C5CE7", "Фиолетовый"),
                            ("#00B894", "Зеленый"),
                            ("#FD79A8", "Розовый"),
                            ("#FDCB6E", "Желтый"),
                            ("#636E72", "Серый"),
                            ("#74B9FF", "Светло-голубой"),
                            ("#55EFC4", "Мятный"),
                            ("#FFEAA7", "Светло-желтый"),
                            ("#D63031", "Темно-красный"),
                            ("#00CEc9", "Бирюзовый 2"),
                            ("#0984E3", "Синий"),
                            ("#B2BEC3", "Светло-серый"),
                            ("#E17055", "Коралловый"),
                            ("#FAB1A0", "Светло-оранжевый"),
                            ("#A29BFE", "Светло-фиолетовый"),
                            ("#81ECEC", "Светло-бирюзовый"),
                        ],
                        default="#3B82F6",
                        max_length=7,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Ежемесячно"),
                            ("weekly", "Еженедельно"),
                            ("yearly", "Ежегодно"),
                            ("custom", "Произвольный"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бюджет категории",
                "verbose_name_plural": "Бюджеты категорий",
                "ordering": ["-created_at"],
            },
        ),
    ]
