# Generated by Django 4.2.16 on 2025-08-31 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("wallet", "Кошелек"),
                            ("credit-card", "Кредитная карта"),
                            ("bank", "Банк"),
                            ("cash", "Наличные"),
                            ("piggy-bank", "Копилка"),
                            ("card", "Карта"),
                            ("money-bill", "Деньги"),
                            ("coins", "Монеты"),
                            ("savings", "Сбережения"),
                            ("investment", "Инвестиции"),
                            ("digital-wallet", "Цифровой кошелек"),
                            ("mobile-wallet", "Мобильный кошелек"),
                            ("crypto-wallet", "Крипто-кошелек"),
                            ("debit-card", "Дебетовая карта"),
                            ("prepaid-card", "Предоплаченная карта"),
                        ],
                        default="wallet",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF6B6B", "Красный"),
                            ("#4ECDC4", "Бирюзовый"),
                            ("#45B7D1", "Голубой"),
                            ("#F9A826", "Оранжевый"),
                            ("#6C5CE7", "Фиолетовый"),
                            ("#00B894", "Зеленый"),
                            ("#FD79A8", "Розовый"),
                            ("#FDCB6E", "Желтый"),
                            ("#636E72", "Серый"),
                            ("#74B9FF", "Светло-голубой"),
                            ("#55EFC4", "Мятный"),
                            ("#FFEAA7", "Светло-желтый"),
                            ("#D63031", "Темно-красный"),
                            ("#00CEc9", "Бирюзовый 2"),
                            ("#0984E3", "Синий"),
                            ("#B2BEC3", "Светло-серый"),
                            ("#E17055", "Коралловый"),
                            ("#FAB1A0", "Светло-оранжевый"),
                            ("#A29BFE", "Светло-фиолетовый"),
                            ("#81ECEC", "Светло-бирюзовый"),
                        ],
                        default="#3B82F6",
                        max_length=7,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("exclude_from_total", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(default="RUB", max_length=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transfers",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "to_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transfers",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_wallet_name_per_user"
            ),
        ),
    ]
